### ISSUE TITLE
Occasional failure to load artwork

### ISSUE THREAD

**Issue by jnj** [jnj/NeonMeate#10]
```
Traceback (most recent call last):
  File "/home/josh/Programs/neonmeate/neonmeate/ui/app.py", line 116, in _on_song_changed
    self._art_cache.fetch(covpath, None, None)
  File "/home/josh/Programs/neonmeate/neonmeate/artcache.py", line 19, in fetch
    gio_file = Gio.File.new_for_path(file_path)
TypeError: Argument 0 does not allow None as a value
```

**Comment by jnj** [comment]
unable to repro in a long time
