### ISSUE TITLE
MPD heartbeat occasionally times out

### ISSUE THREAD

**Issue by jnj** [jnj/NeonMeate#9]
If this happens, should catch and reconnect.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/josh/Programs/neonmeate/neonmeate/nmasync.py", line 38, in _repeat
    self._scheduler.run()
  File "/usr/lib/python3.7/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/home/josh/Programs/neonmeate/neonmeate/mpd/mpdlib.py", line 205, in _on_hb_interval
    self._mpd_status = self._client.status()
  File "/home/josh/Programs/neonmeate/neonmeate/mpd/mpdlib.py", line 104, in status
    return self._client.status()
  File "/home/josh/Programs/neonmeate/venv/lib/python3.7/site-packages/mpd/base.py", line 381, in mpd_command
    return wrapper(self, name, args, callback)
  File "/home/josh/Programs/neonmeate/venv/lib/python3.7/site-packages/mpd/base.py", line 473, in _execute
    return retval()
  File "/home/josh/Programs/neonmeate/venv/lib/python3.7/site-packages/mpd/base.py", line 368, in command_callback
    res = function(self, self._read_lines())
  File "/home/josh/Programs/neonmeate/venv/lib/python3.7/site-packages/mpd/base.py", line 317, in _parse_object
    objs = list(self._parse_objects(lines))
  File "/home/josh/Programs/neonmeate/venv/lib/python3.7/site-packages/mpd/base.py", line 224, in _parse_objects
    for key, value in self._parse_pairs(lines):
  File "/home/josh/Programs/neonmeate/venv/lib/python3.7/site-packages/mpd/base.py", line 219, in _parse_pairs
    for line in lines:
  File "/home/josh/Programs/neonmeate/venv/lib/python3.7/site-packages/mpd/base.py", line 538, in _read_lines
    line = self._read_line()
  File "/home/josh/Programs/neonmeate/venv/lib/python3.7/site-packages/mpd/base.py", line 518, in _read_line
    line = self._rfile.readline()
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

**Comment by jnj** [comment]
Haven't seen this in a while. It might have been fixed inadvertently.

**Comment by jnj** [comment]
Haven't seen this happen in quite a while, so closing.
